jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn clean test

      - name: Generate JaCoCo Coverage Report
        run: mvn surefire-report:report

#      - name: Generate JaCoCo Coverage Report
#        run: mvn jacoco:report


      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: JaCoCo Coverage Report
          path: target/site/  # Path where JaCoCo reports are generated